# Generated by Django 2.2.1 on 2019-08-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0003_auto_20190815_2133'),
        ('kilometers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='uren.Activity'),
        ),
        migrations.AddField(
            model_name='trip',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='uren.Project'),
        ),
    ]
