# Generated by Django 2.2.1 on 2019-08-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilometers', '0002_auto_20190815_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='allowance',
        ),
    ]
