# Generated by Django 2.2.1 on 2019-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilometers', '0003_remove_trip_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
