# Generated by Django 2.2.1 on 2019-08-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0002_auto_20190812_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['code'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='projecthours',
            options={'ordering': ['-date', 'project', 'activity'], 'verbose_name_plural': 'Project hours'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code']},
        ),
    ]
