# Generated by Django 2.2.1 on 2019-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0003_auto_20190815_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
