# Generated by Django 2.2.1 on 2019-10-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0004_activity_is_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthours',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projecthours',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
