# Generated by Django 2.2.1 on 2019-10-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0005_auto_20191007_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthours',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
